version: '3.8'

services:
  novel-reader:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./public/images:/app/public/images
      - ./chapters:/app/chapters
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    container_name: novel-reader-app
