version: '3.8'

services:
  novel-reader:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./public/images:/app/public/images
      - ./novel-data:/app/novel-data
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    container_name: novel-reader-app
    # 生产环境资源限制
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/novel"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
